### ISSUE TITLE
右上角能增加未读提醒吗？

### ISSUE THREAD

**Issue by kinaka** [liaoliao666/v2ex#10]
右上角增加未读提醒的话，更加方便直观，还有能接入iOS的通知推送吗？感谢

**Comment by liaoliao666** [comment]
目前主页左上角头像已经有了未读提醒。
至于iOS的消息推送得需要后端的支持，而本项目只涉及客户端的实现，所以这个是无法实现的。

**Comment by cs-moushuai** [comment]
> 目前主页左上角头像已经有了未读提醒。 至于iOS的消息推送得需要后端的支持，而本项目只涉及客户端的实现，所以这个是无法实现的。

要是有这个功能用得就舒服多了

**Comment by liaoliao666** [comment]
> > 目前主页左上角头像已经有了未读提醒。 至于iOS的消息推送得需要后端的支持，而本项目只涉及客户端的实现，所以这个是无法实现的。
> 
> 要是有这个功能用得就舒服多了

不在首页的话也会有消息推送提示你有未读消息的。
