### ISSUE TITLE
提高启动速度

### ISSUE THREAD

**Issue by TCOTC** [liaoliao666/v2ex#102]
我手机上冷启动大概要 6、7 秒，有点太慢了

**Comment by liaoliao666** [comment]
不至于吧，你啥手机

**Comment by TCOTC** [comment]
oppo k9 pro 

但我感觉跟我手机关系不大，其他应用基本都是 3s 内就能启动

**Comment by liaoliao666** [comment]
后续会有个适配新架构的版本，可能会对冷启动有优化，更新了我会在这通知你

**Comment by TCOTC** [comment]
感谢🙏

反正我这里就很奇怪，点开 APP 就会在 LOGO 卡好几秒

**Comment by liaoliao666** [comment]
更新了下底层框架的新架构，可能有优化

**Comment by TCOTC** [comment]
我已经换手机了，在新手机没遇到这个问题了😃

我先关闭了。
