### ISSUE TITLE
搜索建议增加谷歌！

### ISSUE THREAD

**Issue by Qroxyquan** [liaoliao666/v2ex#108]

**Comment by liaoliao666** [comment]
已经支持了的，你点搜索框右侧的图标，选择谷歌搜索





------------------ 原始邮件 ------------------
From: 林某人 ***@***.***&gt;
发送时间: 04/20/2024, 13:32
To: liaoliao666/v2ex ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
Subject: Re: [liaoliao666/v2ex] 搜索建议增加谷歌！ (Issue #108)

**Comment by Qroxyquan** [comment]
哦 看到了，入口太深没注意到😅谢谢！
