### ISSUE TITLE
代理请求失败

### ISSUE THREAD

**Issue by xiaokaRepo** [liaoliao666/v2ex#109]
版本1.7.4
iOS版本17.4.1
韩国节点，网页版访问正常，其他v2ex客户端访问正常
尝试过重装，清理缓存均无法解决
![image](https://github.com/liaoliao666/v2ex/assets/141160532/657fab40-818c-4175-816c-2781d2e81e87)

**Comment by liaoliao666** [comment]
只有这个节点么，切换其他节点可以访问不

**Comment by xiaokaRepo** [comment]
使用Wi-Fi网络下又正常了，感谢作者的软件很棒🎉
