### ISSUE TITLE
URL Scheme 搜索中有中文的话会导致报错，英文没问题

### ISSUE THREAD

**Issue by mzwlevi** [liaoliao666/v2ex#110]
Launch Center Pro 中的设置

![V2EX](https://github.com/liaoliao666/v2ex/assets/78029539/87797b1a-9e65-4f72-875d-9bfb000d3581)

![IMG_0835](https://github.com/liaoliao666/v2ex/assets/78029539/f471edca-b5aa-46d2-b1ca-e54460703432)
![IMG_0834](https://github.com/liaoliao666/v2ex/assets/78029539/90a6cd11-cedd-4c27-b70c-6182de70cdc7)
![IMG_0837](https://github.com/liaoliao666/v2ex/assets/78029539/5b79cd8a-6d7f-4346-8f4c-c87bf856e984)
![IMG_0836](https://github.com/liaoliao666/v2ex/assets/78029539/e215bdc2-64ac-4a76-96f7-8367ef27cb55)

**Comment by mzwlevi** [comment]
使用文档中的例子也一样
![Open URLs](https://github.com/liaoliao666/v2ex/assets/78029539/a61956f9-84be-490f-b81d-2dd42e949dd5)
![Screenshot 2024-06-15 at 15 41 31](https://github.com/liaoliao666/v2ex/assets/78029539/e89910fa-f911-4a3b-bc8e-d5d7186c14e7)

**Comment by liaoliao666** [comment]
嗯嗯，最近特别特别忙，几乎没时间看这个项目，等忙完了会重新优化一波的

**Comment by liaoliao666** [comment]
已修复
