### ISSUE TITLE
求教 twrnc 相关技术问题

### ISSUE THREAD

**Issue by faimin** [liaoliao666/v2ex#114]
本人`RN`新手，据我了解内联的`style` 每次执行都是一个全新的对象，会导致重复渲染。想请问大佬，[twrnc](https://github.com/jaredh159/tailwind-react-native-classnames) 这个库转换样式后生成的是`inline style`还是被全局对象存储的 `style`呢，会存在重复渲染问题吗？

**Comment by liaoliao666** [comment]
他做了优化的，只要是纯字符串就不会生成一个全新的对象

**Comment by faimin** [comment]
> 他做了优化的，只要是纯字符串就不会生成一个全新的对象

请问大佬是在哪里看到过依据吗？这几天我在网上都没有搜到相关的资料

**Comment by liaoliao666** [comment]
看源码。或者你写个memo的组件试试就知道了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年7月30日(星期二) 晚上7:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [liaoliao666/v2ex] 求教 twrnc 相关技术问题 (Issue #114)














  
他做了优化的，只要是纯字符串就不会生成一个全新的对象
  
请问大佬是在哪里看到过依据吗？这几天我在网上都没有搜到相关的资料
