### ISSUE TITLE
发现一个bug, 我改造成了小程序，

### ISSUE THREAD

**Issue by dagouzhi** [liaoliao666/v2ex#115]
现有一个bug，无法正确解析，可以尝试更改以下文件

`https://github.com/liaoliao666/v2ex/blob/a46d580c089e1cc3d47e42c79839909c949da086/servicies/helper.ts#L129`
```
-const $topicItem = $this.find('table > tbody > tr:first-child')
+const $topicItem = $this.find('table tr:first-child')
```

### 使用红糖云服app 扫码添加小程序

[![小程序码](https://github.com/htyf-mp-community/v2ex/raw/main/qrcode.png)](https://share.dagouzhi.com/#/pages/index/index?data=%7B%22type%22%3A%22app%22%2C%22name%22%3A%22v2ex%22%2C%22projectname%22%3A%22v2ex%22%2C%22appid%22%3A%22dgz996_v2ex%22%2C%22appUrlConfig%22%3A%22https%3A%2F%2Fraw.githubusercontent.com%2Fhtyf-mp-community%2Fv2ex%2Fmain%2Fdgz%2Fbuild%2Foutputs%2Fapp.json%22%2C%22zipUrl%22%3A%22https%3A%2F%2Fraw.githubusercontent.com%2Fhtyf-mp-community%2Fv2ex%2Fmain%2Fdgz%2Fbuild%2Foutputs%2Fdist.dgz%22%7D)

>更多小程序demo 请查看[https://github.com/htyf-mp-community/demo](https://github.com/htyf-mp-community/demo)

**Comment by liaoliao666** [comment]
ok，已经改了

**Comment by dagouzhi** [comment]
已同步更新
