### ISSUE TITLE
ios客户端 首页未正常加载

### ISSUE THREAD

**Issue by you-hengh** [liaoliao666/v2ex#12]
![IMG_018F422E18A9-1](https://user-images.githubusercontent.com/34816426/211141115-0803d9e6-f0f9-4d26-87f2-a1581b0e8e1f.jpg)

刷新缓存也没效果, 很奇怪

**Comment by liaoliao666** [comment]
最新板块我也出现过一次这个问题，但过一天又恢复正常了，很奇怪。
我猜测是做了人机验证，你可以尝试在浏览器打开最新板块，如果出现人机验证的话就是这个问题了。

**Comment by you-hengh** [comment]
> 最新板块我也出现过一次这个问题，但过一天又恢复正常了，很奇怪。 我猜测是做了人机验证，你可以尝试在浏览器打开最新板块，如果出现人机验证的话就是这个问题了。

<img width="1318" alt="image" src="https://user-images.githubusercontent.com/34816426/211155413-32a0757f-7be7-4d41-ab7a-7895c719e392.png">


我都不知道最新板块 是哪个板块

**Comment by liaoliao666** [comment]
<img width="583" alt="Screenshot 2023-01-08 at 05 51 45" src="https://user-images.githubusercontent.com/26479949/211171573-794f23e1-40cb-4253-a7b3-5c51f728361b.png">
图中更多新主题那里

**Comment by liaoliao666** [comment]
最新版本已增加503错误校验
