### ISSUE TITLE
IOS 审核问题

### ISSUE THREAD

**Issue by liaoliao666** [liaoliao666/v2ex#14]
> 最近iOS一直审核不通过，对这方面有经验的可以在这留言帮忙解决一下😭，以下是审核的回复

Hello,

The issues we previously identified still need your attention.

If you have any questions, we are here to help. Reply to this message in App Store Connect and let us know. 

Guideline 4.1 - Design - Copycats

Your app or its metadata appears to contain potentially misleading content. Specifically, your app includes content that resembles https://www.v2ex.com/ without the necessary authorization.

Next Steps

Please demonstrate your relationship with any third-party brand owners represented in your app.

 

iOS App 1.1.7App 版本
拒绝原因：
4.1.0 Design: Copycats

**Comment by ddqp** [comment]
增加testfight ？

**Comment by liaoliao666** [comment]
> 增加testfight ？

为啥，不是一个问题吧

**Comment by liaoliao666** [comment]
进度更新：
今天和苹果审核通了电话讨论了关于审核不通过的问题，审核那边是需要v2ex对本应用及开发者的授权。
然后这两天我会联系v2ex那边看能不能拿到授权。

**Comment by livid** [comment]
收到你的邮件，我把我的回复在这里也贴一下。

---

你好，

我是 V2EX 站长。我也很想帮你。我看到你在 GitHub 上的 issue 里提到的描述了。

我不太清楚的是，Apple 那边需要一个什么样的材料来证明？及我又如何向 Apple 证明我确实有这个权威来给出这样的授权？根据我之前和 Apple 在类似问题上的一些经历，一个建议是可以在名称和描述信息里，加强对「第三方客户端」这个性质的描述。比如这里有一个参考：

https://apps.apple.com/us/app/octal-for-hacker-news/id1308885491

App Store 里应用的名称通常是 Something for Something 这样的命名，比如上面的例子里，一个 HN 客户端的名字是 Octal for Hacker News。而如果直接叫 Hacker News Hi，那是会有商标侵权的观感。

**Comment by liaoliao666** [comment]
> 收到你的邮件，我把我的回复在这里也贴一下。
> 
> 你好，
> 
> 我是 V2EX 站长。我也很想帮你。我看到你在 GitHub 上的 issue 里提到的描述了。
> 
> 我不太清楚的是，Apple 那边需要一个什么样的材料来证明？及我又如何向 Apple 证明我确实有这个权威来给出这样的授权？根据我之前和 Apple 在类似问题上的一些经历，一个建议是可以在名称和描述信息里，加强对「第三方客户端」这个性质的描述。比如这里有一个参考：
> 
> https://apps.apple.com/us/app/octal-for-hacker-news/id1308885491
> 
> App Store 里应用的名称通常是 Something for Something 这样的命名，比如上面的例子里，一个 HN 客户端的名字是 Octal for Hacker News。而如果直接叫 Hacker News Hi，那是会有商标侵权的观感。

十分感谢🙏。我打算将应用改名为 V2Fun, 不用非常官方的材料。只需要您在口头上，在这里留下回复或者邮件。能证明有对应用名： V2Fun。及应用 Apple Id: 1659591551。进行授权就可以了

**Comment by livid** [comment]
Dear Apple App Store Reviewer,

V2EX is a developer community. Our open API allows third-party developers to create a variety of apps, and you can find more information about it on our website at https://www.v2ex.com/help/api.

If you have any questions or need additional verification, please don't hesitate to reach out to us at [hello@v2ex.com](mailto:hello@v2ex.com). Our team will be more than happy to assist you.

Best,

V2EX Webmaster

**Comment by liaoliao666** [comment]
@livid 感谢，希望您能度过愉快的一天

**Comment by livid** [comment]
祝顺利 :) 如果后续他们通过邮件联系 V2EX，我们会配合回复。
