### ISSUE TITLE
右侧移动条错位

### ISSUE THREAD

**Issue by Thecosy** [liaoliao666/v2ex#15]
![427A7294-09DA-424C-89FC-2BBFF53F9EE7](https://user-images.githubusercontent.com/87817554/212554199-aabe36fa-9c8c-487e-9082-77baa708d1c6.jpeg)
![DCDCCAC9-9DD5-47B9-966B-9B046C927C6A](https://user-images.githubusercontent.com/87817554/212554202-2365f72a-af47-4d67-8721-de61d516af1d.jpeg)
![D88B9B74-9DAB-4292-BE2B-DAB2CA1EC3B9](https://user-images.githubusercontent.com/87817554/212554203-1b974823-816d-4bf9-b469-8b38b92a67d0.png)
设备：苹果12
如图

**Comment by liaoliao666** [comment]
下个版本会修复，等审核通过更新下就好

**Comment by Thecosy** [comment]
ok

**Comment by liaoliao666** [comment]
最新版已修复
