### ISSUE TITLE
搜索功能无法使用，建议直接调用 Google 搜索

### ISSUE THREAD

**Issue by ddqp** [liaoliao666/v2ex#17]
如题

**Comment by liaoliao666** [comment]
可以用啊，你挂梯子了没有

**Comment by ddqp** [comment]
挂了啊，就是搜索不出来

**Comment by ddqp** [comment]
好像是无法访问，www.sov2ex.com

网页版可以在 v2 搜索

**Comment by liaoliao666** [comment]
> 好像是无法访问，www.sov2ex.com
> 
> 网页版可以在 v2 搜索

网页版v2是直接调用谷歌搜索的。可以检查一下自己的网络，因为 sov2ex 网站没有挂。
