### ISSUE TITLE
iOS 客户端 无法登录

### ISSUE THREAD

**Issue by hywhuangyuwei** [liaoliao666/v2ex#18]
无论是之前的应用内使用 Google 登录
还是最新版本 - 使用网页登录 - Google 登录
或者是直接在 App 内输入用户名密码
在登录完成后都没有登录状态

**Comment by liaoliao666** [comment]
请问是1.1.7版本么

**Comment by liaoliao666** [comment]
谢谢老哥这么支持🙏。
另外你系统版本是不是16.2及以上。我断断续续都有在看这个问题，但周围实在找不到能复现的机子。所以都是每次发版靠你们测😂，效率很低，但接下来肯定会一直跟进的

**Comment by liaoliao666** [comment]
已经有个老哥加我 QQ 协助了，但不能在开发环境的话效率还是太低了。
我这阵子再研究研究，有进展我会在这 issue 下更新的。

**Comment by alexlee728** [comment]
遇到同样问题，iOS 16.3

**Comment by liaoliao666** [comment]
@alexlee728 @hywhuangyuwei 
兄弟们，可以更新最新版本试试

**Comment by alexlee728** [comment]
> @alexlee728 @hywhuangyuwei
> 兄弟们，可以更新最新版本试试

还是不可以

**Comment by liaoliao666** [comment]
@alexlee728 
是能登录还是登都登不了

**Comment by alexlee728** [comment]
> @alexlee728
> 是能登录还是登都登不了

不可以登陆，一闪而过，状态还是未登录。删除app重新安装的

**Comment by liaoliao666** [comment]
你一闪而过之后，可以删掉进程重进一下app试一下

**Comment by alexlee728** [comment]
> 你一闪而过之后，可以删掉进程重进一下app试一下

试过了，不行

**Comment by liaoliao666** [comment]
有点蚌埠不住，还有个办法还没试，这两天我再上个版本

**Comment by liaoliao666** [comment]
@alexlee728 @hywhuangyuwei 
又又又更新了一版，兄弟们再试试

**Comment by alexlee728** [comment]
1.2.0版本还是不正常

**Comment by liaoliao666** [comment]
一样的问题么

**Comment by alexlee728** [comment]
> 一样的问题么

是的

**Comment by liaoliao666** [comment]
有点没辙，必须找到个能复现的手机才能继续调下去了

**Comment by kid-oh** [comment]
同样的问题 ios一直最新系统 软件也一直更新 没有一次有登录状态😂

**Comment by liaoliao666** [comment]
![Screenshot 2023-01-31 at 10 53 03](https://user-images.githubusercontent.com/26479949/215650936-90820725-b19f-4a02-aec7-ee15a0c894ca.png)
@kid-oh @alexlee728 
有个问题，你们v2ex的侧栏上有图片里圈中的金钱么

**Comment by kid-oh** [comment]
> ![Screenshot 2023-01-31 at 10 53 03](https://user-images.githubusercontent.com/26479949/215650936-90820725-b19f-4a02-aec7-ee15a0c894ca.png)
> @kid-oh @alexlee728
> 有个问题，你们v2ex的侧栏上有图片里圈中的金钱么

没有 一直都是“点击登录”

**Comment by liaoliao666** [comment]
我好像找到问题在哪了，你可以截个图现在上什么样的么

**Comment by kid-oh** [comment]
> 我好像找到问题在哪了，你可以截个图现在是什么样的么

就是和刚下载的一样 没登录状态后我就没看了

**Comment by liaoliao666** [comment]
你好像误会了，我说的是电脑上访问后右边栏是什么样子的，如果可以的话可以把电脑上返回的dom结构也发出来

**Comment by kid-oh** [comment]
> 你好像误会了，我说的是电脑上访问后右边栏是什么样子的，如果可以的话可以把电脑上返回的dom结构也发出来

![5D7E67AF-3C70-415A-98E4-878B98E2845C](https://user-images.githubusercontent.com/30406467/215653211-a1e3f783-150d-4117-a91d-30c7abea1676.png)
不好意思 我不懂那个dom结构😂金钱确实没显示出来

**Comment by liaoliao666** [comment]
那就是了

**Comment by liaoliao666** [comment]
问题原因：
很难绷得住的是我是拿是否有金钱去判断是否登录的，所以一直考虑的方向就错了。这个确实是代码问题，没有考虑过这个情况，下个版本会对关闭`显示余额`做个兼容

另外：
登录上去后，再在设置里打开性能模式然后重新试一下登录，如果没有问题在下一个版本会将性能模式删除掉，以后就默认走性能模式去登录。

**Comment by kid-oh** [comment]
登录后打开性能模式再登录还是一样的 我等更新吧。另外复制的功能不能选中，只能复制当前一整段句子

**Comment by liaoliao666** [comment]
> 登录后打开性能模式再登录还是一样的 我等更新吧。另外复制的功能不能选中，只能复制当前一整段句子

有登录成功么
复制选中的在计划里，实现有点麻烦得过几个版本才会支持。

**Comment by kid-oh** [comment]
就是输完验证码跳转完就没了，还是显示“点击登录”，用网页登录也是如此，不知道算不算成功登录😂

**Comment by liaoliao666** [comment]
> ![image](https://user-images.githubusercontent.com/26479949/215653821-93cd4fe2-d791-4b03-bd87-a1bf4d3d368b.png)
> 
> 那就是了，你在设置里把显示余额勾上就能登录了

@kid-oh 有安装这里说的，先开启`显示余额`再尝试么

**Comment by kid-oh** [comment]
打开余额显示后app自动登录了，这个开关还要电脑网页端才能打开 手机端没有

**Comment by liaoliao666** [comment]
@hywhuangyuwei @alexlee728 
再更新下就好了
