### ISSUE TITLE
Url scheme

### ISSUE THREAD

**Issue by gloryofchina** [liaoliao666/v2ex#21]
您好，不知道是否支持url scheme？app搜索的的url scheme是什么呢？

**Comment by liaoliao666** [comment]
暂时没有支持url scheme
你是想端外呼起搜索页面么

**Comment by gloryofchina** [comment]
是的，配合快捷指令直接搜索还是很方便的，希望支持

**Comment by liaoliao666** [comment]
可以的，加入待办

**Comment by gloryofchina** [comment]
已经加了，速度真快，赞👍。v2fun划掉后台，直接用url外部调用，搜索可以拉起，但是搜索界面左上角的返回箭头点击无响应，不知道是否是bug。

**Comment by liaoliao666** [comment]
是bug，下个改一下

**Comment by liaoliao666** [comment]
已解决
