### ISSUE TITLE
App内网页登录使用Sing in with Google发生错误

### ISSUE THREAD

**Issue by xiaohundun** [liaoliao666/v2ex#22]
禁止访问：发生了授权错误
You can’t sign in from this screen because this app doesn’t comply with Google’s secure browsers policy. If this app has a website, you can open a web browser and try signing in from there.

You can let the app developer know that this app doesn’t comply with Google’s secure browsers policy. 详细了解此错误
如果您是“V2EX”的开发者，请参阅错误详情。
错误 403： disallowed_useragent

我觉得跟App无关，但是我在PC上是可以用Google登陆的呀= =

**Comment by liaoliao666** [comment]
明天更新下就好了

**Comment by xiaohundun** [comment]
可以了，感谢作者
