### ISSUE TITLE
帖子内容渲染出来的HTML中的P元素在手机上可以滚动

### ISSUE THREAD

**Issue by xiaohundun** [liaoliao666/v2ex#24]
一不小心就会滚到。。对使用也造成了些困扰

**Comment by liaoliao666** [comment]
可以发下帖子ID么，另外是安卓还是iOS

**Comment by xiaohundun** [comment]
设备iOS16.3，16.2应该也一样，我才升级的16.3

帖子：[912777](https://www.v2ex.com/t/912777)

**Comment by liaoliao666** [comment]
手机型号是多少，我这边没有复现这个情况

**Comment by xiaohundun** [comment]
iPhone 13 Pro，16.3，稍等我录屏吧

**Comment by xiaohundun** [comment]
https://user-images.githubusercontent.com/38812912/216505637-017b4abc-a69a-443f-8e68-5c0b764e2df6.mp4

**Comment by liaoliao666** [comment]
感谢你的时间，这两天我会再发布一版

**Comment by xiaohundun** [comment]
> 感谢你的时间，这两天我会再发布一版

好的，感谢作者～
