### ISSUE TITLE
图片显示不完全，且中心点不确定

### ISSUE THREAD

**Issue by BahuangShanren** [liaoliao666/v2ex#26]
测试环境：Android 11
软件版本：1.2.3

### 图片显示不完全

图片只显示一部分，像是以图片的中心为中心，做了正方形裁剪，比如这张图片：

<img src="https://user-images.githubusercontent.com/48022216/216908456-e72be869-06f6-420d-84ca-7a46e1dfe519.png" height="400px" width="auto">

V2Fun是这么显示的：

<img src="https://user-images.githubusercontent.com/48022216/216907532-49039116-0dc4-4214-a069-2de3935c9001.png" height="800px" width="auto">

正常显示应该是这样的：

<img src="https://user-images.githubusercontent.com/48022216/216907652-82792953-47d5-414e-9061-b3ca2133dd09.png" height="800px" width="auto">

图片点开后仍然不能完全显示，而且出现了下面“中心点不确定”的问题。

### 中心点不确定

图片点开后，图片并不以原本的中心点展开显示，不太好描述，看图片吧，以下两种效果交替出现:

<img src="https://user-images.githubusercontent.com/48022216/216908732-4e2651ed-7b34-48c0-92e1-783409163031.png" height="800px" width="auto">

点击右上角`❌`关闭，再次点开图片，出现以下效果：

<img src="https://user-images.githubusercontent.com/48022216/216908792-e0b437e5-dab0-469c-b7ab-954839319a68.png" height="800px" width="auto">

点击右上角`❌`关闭，再点开图片，又出现第一种效果，总之这两种效果交替出现。

**Comment by liaoliao666** [comment]
是所有图片还是只有这个图片，如果是所有图片之前的版本会有这个问题么

**Comment by BahuangShanren** [comment]
当然试过了其他图片。

所有图片都只显示其被正方形裁剪后的部分。

图片点开后的显示效果，所有图片也都有所谓“中心点不确定”的两种不同效果。
但是对于有些图片，点开图片再关上图片，两种效果并不是 **依次** 交替出现的，而是 **随机** 交替出现，比如对于这张图片：

![Google](https://user-images.githubusercontent.com/48022216/216956116-c71c4b90-8284-4fc2-94f5-f55eccecb6f5.png)

以下两种效果随机交替出现：

<img src="https://user-images.githubusercontent.com/48022216/216956952-7288814c-ac80-48a9-a50c-03c8703271cb.png" height="800px" width="auto">

<img src="https://user-images.githubusercontent.com/48022216/216957001-be7b71f0-7c5e-4d6e-a363-23e66fb197c0.png" height="800px" width="auto">

**Comment by liaoliao666** [comment]
我看你给的例子都是在预览图片时出现这个问题，如果在图片在帖子详情中(也就是没点开预览时)会不会有这个问题

**Comment by BahuangShanren** [comment]
没理解你说的`预览图片`和`帖子详情`分别指什么状态，好像模糊了两个概念，我姑且猜一下。
既然“点开预览”，那`预览图片`是指：
<img src="https://user-images.githubusercontent.com/48022216/216908732-4e2651ed-7b34-48c0-92e1-783409163031.png" height="800px" width="auto">
而`帖子详情`指：
<img src="https://user-images.githubusercontent.com/48022216/216907532-49039116-0dc4-4214-a069-2de3935c9001.png" height="800px" width="auto">
**是这样吗？**

-----------------------------------------------------------------
**我有个更清晰的说法：**
下图的帖子的状态不就已经是`帖子详情`了？把这时图片的显示状态叫做`图片预览状态`，
<img src="https://user-images.githubusercontent.com/48022216/216907532-49039116-0dc4-4214-a069-2de3935c9001.png" height="800px" width="auto">
点击图片后，把下图叫做`图片详情状态`不是更合适吗？
<img src="https://user-images.githubusercontent.com/48022216/216908732-4e2651ed-7b34-48c0-92e1-783409163031.png" height="800px" width="auto">

**Comment by liaoliao666** [comment]
你的解释很到位。那借用你的说法
是只在 `图片详情状态` 出现这个问题还是二者都存在这个问题

**Comment by liaoliao666** [comment]
明白了，`图片预览状态` 也有问题的话就很棘手了。而且棘手的原因和之前的登录问题一样，手上没有复现的机子。
我这两天多测测看怎么解决

**Comment by liaoliao666** [comment]
@BahuangShanren 
https://expo.dev/artifacts/eas/jB68F7b3QjxK55vGzB96Ap.apk
看一下图片还有没有问题在上面链接的这个版本。
另外新增了markdown 语法的支持

**Comment by BahuangShanren** [comment]
`图片预览状态`的问题仍然存在；但是`图片详情状态`已经正常了，可以完全显示图片。

**Comment by liaoliao666** [comment]
麻烦提供下手机型号及版本号，我试试在模拟器能不能复现这个问题

**Comment by BahuangShanren** [comment]
这似乎和手机型号以及系统版本号并无太大关系。
我在两个安卓实体机和数个Genymotion中的虚拟机中均复现该问题。
- Redmi K40（基于Android 12的Pixel Experience）
- Redmi Note 5（基于Android 11的Lineage OS）
- Genymotion中的Google Pixel 3（Android 9~11）

**Comment by liaoliao666** [comment]
@BahuangShanren 下载最新的包应该就好了

**Comment by BahuangShanren** [comment]
非常棒，问题均被解决。
