### ISSUE TITLE
希望支持切换发帖语法

### ISSUE THREAD

**Issue by BahuangShanren** [liaoliao666/v2ex#27]
希望能在`V2EX原生格式`和`Markdown格式`之间切换

**Comment by BahuangShanren** [comment]
也许有人写大段文字时需要markdown丰富的格式呢。
的确不算是很重要的功能，可以考虑作为未来更新的feature

**Comment by liaoliao666** [comment]
哦哦，那下个版本会把markdown语法加上

**Comment by BahuangShanren** [comment]
`Markdown格式`正常。

对于发帖界面右上角的`预览`按钮，能否将`预览`按钮改为点击后变成`退出预览`，来强调交互逻辑？

因为我在使用时发现了这种情况：
查看预览后，想退出预览，但下意识地点击了左上角返回按钮，直接退到软件主界面了，再点击发帖，刚刚编辑的草稿都丢失了。

**Comment by liaoliao666** [comment]
可以的，另外如果你想调试的话一会可以拉下最新的commit。避免和你的冲突了。

**Comment by liaoliao666** [comment]
已支持
