### ISSUE TITLE
不支持打开该链接 版本 1.2.4

### ISSUE THREAD

**Issue by moonheart** [liaoliao666/v2ex#28]
https://www.v2ex.com/t/915099 这个帖子里面的贴图中的链接无法打开，奇怪的是别的可以打开

![Screenshot_2023-02-11-14-44-17-611_com liaoliao666 v2ex](https://user-images.githubusercontent.com/15916990/218244937-dfdad74a-7e8e-41c7-9f25-31653437d6cb.jpg)

**Comment by liaoliao666** [comment]
https://expo.dev/artifacts/eas/uJdZRdcfxwVgDAsBRsW8x8.apk
兄弟，试一下上面这个下载地址的

**Comment by moonheart** [comment]
> [expo.dev/artifacts/eas/uJdZRdcfxwVgDAsBRsW8x8.apk](https://expo.dev/artifacts/eas/uJdZRdcfxwVgDAsBRsW8x8.apk) 兄弟，试一下上面这个下载地址的

还是不行，同样的错误提示

**Comment by liaoliao666** [comment]
兄弟更新到 1.2.5 再试试

**Comment by moonheart** [comment]
正常工作了  /close
