### ISSUE TITLE
1.无法分享链接到微信，提示获取资源失败。2.发送按钮属实是太小了。。

### ISSUE THREAD

**Issue by goxofy** [liaoliao666/v2ex#29]

**Comment by goxofy** [comment]
还有打开链接的问题

![Screenshot_2023-02-12-00-13-38-10_737b16d9ed1b2276a8ea34ba9d309da8.jpg](https://user-images.githubusercontent.com/1695416/218268717-3059a1ae-8a3f-45a1-9573-7bfe8e611afc.jpg)

**Comment by liaoliao666** [comment]
https://expo.dev/artifacts/eas/cQqp2sU8RtArmn2HwUidWb.apk
试试这个下载地址的链接能不能打开，还有分享图片的功能已经做好了可以测下有没有问题。

**Comment by BahuangShanren** [comment]
我用的 https://github.com/liaoliao666/v2ex/releases/tag/1.2.5
可以打开链接了，比如 github.com 能直接跳转到 GitHub 客户端。

但是无法分享到微信，显示`获取资源失败`。

另外`图片分享`功能是什么？

@liaoliao666

**Comment by liaoliao666** [comment]
长按图片会有分享按钮

**Comment by liaoliao666** [comment]
我以为的你们说的分享链接是想要分享图片，原来说的是这个😂。后续我再看看这个问题吧

**Comment by goxofy** [comment]
@liaoliao666 打开链接和分享到微信都ok了，发送按钮希望能增大一点，另外貌似是个小bug，就是回复框里输入好内容之后（较少内容），直接点不了发送，必须在末尾加个空格，才能发出去，不知道是不是字数限制？我记得v站本身是没有字数限制的

**Comment by BahuangShanren** [comment]
> https://expo.dev/artifacts/eas/5JD6RtwPcdGJqrEmN2ck9t.apk

@liaoliao666 

- [x] 打开链接
- [x] 分享贴子或楼层回复
- [x] 分享图片
 
> 另外貌似是个小bug，就是回复框里输入好内容之后（较少内容），直接点不了发送，必须在末尾加个空格，才能发出去

@goxofy 

我未能复现

**Comment by goxofy** [comment]
https://user-images.githubusercontent.com/1695416/218351723-614c3dc6-c587-4767-8c85-9fe31c3e5f2e.mp4

**Comment by BahuangShanren** [comment]
@goxofy 奇怪哦，我复现不了。我的系统是Android 11，你的系统是？

**Comment by goxofy** [comment]
@BahuangShanren 我是12，一加

**Comment by liaoliao666** [comment]
这个bug可不小啊，复现不了的修起来都得要花一些时间

**Comment by goxofy** [comment]
其实也不影响，无非就是多加几个空格

**Comment by BahuangShanren** [comment]
Android 12稳定复现，表现为：
输入英文，能够正常发送。
输入中文，发送按钮处于灰显状态，不能点击（点击无效），此时加上一个空格，发送按钮变成正常状态，点击后可以发送。

**Comment by liaoliao666** [comment]
找到问题了，我自己写的一个校验只要少于2个字符就不让发

**Comment by goxofy** [comment]
已解决~
