### ISSUE TITLE
一个节点滑到底之后就不能继续翻看旧主题了吗？

### ISSUE THREAD

**Issue by hsuromky** [liaoliao666/v2ex#31]
一个节点滑到底之后就不能继续翻看旧主题了吗？
我还想继续翻看旧主题该怎么操作

**Comment by liaoliao666** [comment]
在首页侧栏里有个最近浏览选项，点进去可以查看最近24小时的主题

**Comment by hsuromky** [comment]
不是查看历史，而是看完帖子之后怎么查看更多帖子
![Screenshot_2023-02-28-19-34-24-590-edit_com microsoft emmx](https://user-images.githubusercontent.com/117238021/221842370-c7305313-0095-41f3-8ea0-69211c349016.jpg)

**Comment by liaoliao666** [comment]
首先你需要区分 `首页tab` 和 `节点` 这两种列表，如果是 `首页tab` v2ex 本身是没有更多按钮的。
如果是 `节点` 的列表，本身已经是已经有支持到底加载更多帖子的功能

**Comment by liaoliao666** [comment]
而你截图中 `更多` 按钮实际上跳转的是 `首页tab` 中所对应的 `最新` 列表，而不是当前 tab 的更多新内容
