### ISSUE TITLE
希望加入imgur图床

### ISSUE THREAD

**Issue by androidcn** [liaoliao666/v2ex#37]
图床

**Comment by liaoliao666** [comment]
把目前所有问题全部弄完之后才会考虑

**Comment by androidcn** [comment]
> 把目前所有问题全部弄完之后才会考虑

Great

**Comment by androidcn** [comment]
我看就剩下图床了，不能发图，难受

**Comment by liaoliao666** [comment]
到也没有，还有上架谷歌商店的没搞。这个和上架谷歌商店的一起发吧，时间可能要等久点。

**Comment by liaoliao666** [comment]
已支持，不知道和你想的是不是一样的😂

**Comment by androidcn** [comment]
怎么没有 输入用户名和token的选项？

**Comment by liaoliao666** [comment]
哦哦 应该增加一个 `accessToken`，我有点好奇是不是可以取消 `clientId` 只用 `accessToken`

**Comment by androidcn** [comment]
> 哦哦 应该增加一个 `accessToken`，我有点好奇是不是可以取消 `clientId` 只用 `accessToken`

这个 app 授权 三个都要填

![image](https://user-images.githubusercontent.com/271715/232180915-2fc138a3-9523-433a-b87c-5d6188f1717f.jpeg)

**Comment by liaoliao666** [comment]
我对imgur不熟悉啊，它的 api 文档里上传图片只需要 client ID 或 access token 就可以

**Comment by androidcn** [comment]
> 我对imgur不熟悉啊，它的 api 文档里上传图片只需要 client ID 或 access token 就可以

慢慢研究，我也不熟

**Comment by liaoliao666** [comment]
你填一下 client ID 试试，功能应该是没问题，只是有些好奇 client ID 会不会不够安全， 用 access token 安全性比较好。我担心可能会有人觉得这个 app 安全性不太好，会泄露他们的 client ID

**Comment by androidcn** [comment]
> 问题

Android平板

https://www.v2ex.com/t/932786

测试成功

**Comment by liaoliao666** [comment]
仔细想想好像二者也没啥区别，暂时只支持clientId了。
