### ISSUE TITLE
希望能支持在应用内打开链接

### ISSUE THREAD

**Issue by liuw5367** [liaoliao666/v2ex#38]
点击链接会跳转到浏览器，来回切换挺麻烦，而且个人看完网页还得删除safari标签页，希望能支持在应用内打开链接

**Comment by liaoliao666** [comment]
下个版本会在设置上加个开关是否默认浏览器打开

**Comment by liaoliao666** [comment]
已支持

**Comment by liuw5367** [comment]
感谢。已更新试用，但建议应用内浏览器使用系统默认的样式，Github 应用使用的内部浏览器就挺好，可以参考一下

**Comment by liaoliao666** [comment]
由于需要 `浏览器打开` 这个功能，所以样式应该不会改动了。
目前已经可以支持轻度的浏览，重度的话还是推荐浏览器打开吧
