### ISSUE TITLE
会否提交F-Droid

### ISSUE THREAD

**Issue by alaskasquirrel** [liaoliao666/v2ex#39]
是否考虑提交到[F-Droid](https://f-droid.org/)或[IzzyOnDroid](https://apt.izzysoft.de/fdroid/)，便于推广。

**Comment by liaoliao666** [comment]
得闲的时候我会研究一下的，老这么发安卓包也不是个办法

**Comment by linsui** [comment]
@liaoliao666 我来打包怎么样？

**Comment by liaoliao666** [comment]
ok，我没问题

**Comment by linsui** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/15280

**Comment by linsui** [comment]
构建出来的 apk 闪退，有可能是什么原因？

**Comment by liaoliao666** [comment]
再试试，我把expo的sdk降级了

**Comment by linsui** [comment]
还是相同的崩溃。这个问题你能复现吗？

**Comment by liaoliao666** [comment]
再试试呢，还不行就算了😂

**Comment by linsui** [comment]
你讲一下你的构建步骤吧，我试了能想到的地方没什么区别。

**Comment by liaoliao666** [comment]
eas build --local -p android --profile preview
就这一行命令

**Comment by linsui** [comment]
我试试

**Comment by linsui** [comment]
eas 需要账户吗？那肯定是不行的。 :facepalm: 看起来也是调用 gradle

**Comment by liaoliao666** [comment]
eas 需要账户的，随便申请一个就行。
我对原生也不熟，但我这个命令是本地打包的，运行了命令后，除了前面输出了下面这两行，就只涉及到本地的打包了。
```bash
Using remote Android credentials (Expo server)
Using Keystore from configuration: Build Credentials (default)
```

**Comment by linsui** [comment]
我放弃了，我构建的 apk 多了一些 .so 文件但不知道原因。崩溃的原因也不清楚。 :facepalm:

**Comment by liaoliao666** [comment]
好的，已经很感谢你花时间研究了





------------------ 原始邮件 ------------------
From: linsui ***@***.***&gt;
发送时间: 07/07/2024, 15:46
To: liaoliao666/v2ex ***@***.***&gt;
抄送: liaoliao666 ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [liaoliao666/v2ex] 会否提交F-Droid (Issue #39)





 
我放弃了，我构建的 apk 多了一些 .so 文件但不知道原因。崩溃的原因也不清楚。 🤦
