### ISSUE TITLE
Feature Request: 希望增加通过URL Scheme打开具体帖子页面

### ISSUE THREAD

**Issue by hywhuangyuwei** [liaoliao666/v2ex#40]
例如可以通过 v2fun://thread/924456#reply101 直接跳转到 https://www.v2ex.com/t/924456#reply101 对应的帖子。

如果能支持像这样通过URL Scheme唤起，可为本应用解锁更多使用场景和玩法！

**Comment by liaoliao666** [comment]
能支持跳转到帖子。
因为跳转到指定回复之前实现过会有bug，所以跳转到指定回复就不做了。

ps：当然如果你看到有哪个 rn 做的app 能实现这个功能，我可以找它的源码研究一下，把这个功能也加上。

**Comment by liaoliao666** [comment]
已支持
