### ISSUE TITLE
进入app没有动画，没有任何提示，list列表就更新了，体验不佳

### ISSUE THREAD

**Issue by androidcn** [liaoliao666/v2ex#41]
进入app没有动画，没有任何提示，list列表就更新了，体验不佳

大概10s左右就刷新，没有提示，在获取新的数据，希望加入toast提示或者loading hud

**Comment by liaoliao666** [comment]
加了体验也会有点问题，你每切换一次 tab 都会显示 loading，会有顿挫感我觉得

**Comment by androidcn** [comment]
> 加了体验也会有点问题，你每切换一次 tab 都会显示 loading，会有顿挫感我觉得

顶部加个小提示就好啦，不然很突兀，突然就变化

**Comment by liaoliao666** [comment]
之前有考虑过，但是实在找不着地方放了😂

**Comment by androidcn** [comment]
顶部下滑通知呗

**Comment by liaoliao666** [comment]
那就和安卓的下拉刷新loading冲突了，安卓的loading就说顶部下滑通知的。
目前想到的方案可以是，loading状态列表透明的稍微变淡

**Comment by androidcn** [comment]
加油

**Comment by androidcn** [comment]
Good 完美的loading
