### ISSUE TITLE
「需求」关键字新帖提醒，新回复提醒

### ISSUE THREAD

**Issue by androidcn** [liaoliao666/v2ex#42]
「需求」关键字新帖提醒，新回复提醒
本地后台定时刷新某板块如「交易」，设定关键字如[HomePod]，找到新帖，push通知新帖

新回复同理

**Comment by liaoliao666** [comment]
应用外通知得需要服务端的配合，而本应用只涉及 app 端，所以无法实现该功能

**Comment by androidcn** [comment]
本地后台刷新，不是服务器
