### ISSUE TITLE
列表点击无反应

### ISSUE THREAD

**Issue by aoxiangfly** [liaoliao666/v2ex#45]
ios16, iphone8p，iphone14均出现该情况，在全部或者最热列表下下滑，点击帖子无反应，只能刷新当前列表。刷新之后再次下滑，重复出现该问题

**Comment by liaoliao666** [comment]
我也复现了，是之前加入的优化列表性能后出现的bug，今晚会发个版本修复这个问题。

**Comment by liaoliao666** [comment]
已修复
