### ISSUE TITLE
v1.3.4启动时闪退，Android

### ISSUE THREAD

**Issue by zhyoch** [liaoliao666/v2ex#47]
[v1.3.4](https://github.com/liaoliao666/v2ex/releases/tag/1.3.4) 启动时闪退, 卸载重装后仍能复现。测试了几个设备, 从 Android 11 到 13, 均复现。

**Comment by liaoliao666** [comment]
你重新下载试试，依赖库好像有点问题

**Comment by zhyoch** [comment]
已正常
