### ISSUE TITLE
增加更新模式

### ISSUE THREAD

**Issue by vLai2216984540** [liaoliao666/v2ex#49]
一直在用之前的某个版本，然后想更新，没找到，之前没start，找了半天才回来。加油，app用着还不错，这次已start

**Comment by vLai2216984540** [comment]
README.md可以加个付款码，赞助一下。大佬加油💪

**Comment by liaoliao666** [comment]
赞助就不用了，也不差这点钱😂。
下个版本会增加个检查更新功能，不过最近有点忙，最近可能没空维护。

**Comment by androidcn** [comment]
加一下二维码吧，喝杯咖啡也不错

**Comment by liaoliao666** [comment]
新版本已增加检查更新功能
