### ISSUE TITLE
字体大小问题

### ISSUE THREAD

**Issue by zwb124** [liaoliao666/v2ex#51]
app的字体大小只是调节的设置和标题大小，能否给一个能调节帖子内容字体大小的选项，现在的内容字体太小了🙏

**Comment by liaoliao666** [comment]
现在已经是可以调节帖子内容字体大小得

**Comment by zwb124** [comment]
> 现在已经是可以调节帖子内容字体大小得

那为啥我改完了超大字体，设置和标题都变了，唯独内容没有反应呢？ios版本的

**Comment by liaoliao666** [comment]
目前超大和中等就差了2px可能你看不大出来？你可以试试小和超大对比下

**Comment by zwb124** [comment]
额，对我来说那还是有点小了，作者可以考虑伟途亦可斯的处理方式，直接弄个滑块，想调多小多大都随着自己

**Comment by liaoliao666** [comment]
也可以，这周末更新一下

**Comment by liaoliao666** [comment]
目前字体等级也重新调校了，你可以再试试。
因为滑块以百分比的方式实现字体缩放。但是目前几种字体等级的行高及字体大小都是专门调校过的。强行只按百分比来反而体验不是没有现在观感好。

**Comment by zwb124** [comment]
感谢
