### ISSUE TITLE
调整app内通知样式

### ISSUE THREAD

**Issue by lucky-wh** [liaoliao666/v2ex#52]
希望能优化一下app内签到、回复、已复制…之类的通知样式，感觉有点不协调。

**Comment by liaoliao666** [comment]
可以举个例子你想改成什么样的，我参考下

**Comment by liaoliao666** [comment]
可以直接找个其他例子的我抄抄

**Comment by lucky-wh** [comment]
https://git.poker/lucky-wh/images-hotsing/blob/master/20230611/打卡.62v3tnvouuw0.webp?raw=true
https://git.poker/lucky-wh/images-hotsing/blob/master/20230611/打卡-(1).78j7e3ockug0.png?raw=true
试试阿里的那个图标库
