### ISSUE TITLE
ios版评论显示不全

### ISSUE THREAD

**Issue by Silent-wqh** [liaoliao666/v2ex#54]
如题。已经存在一个多月了
图1是网页版，正常显示。
图2是v2fun，评论后半段没显示。
![image](https://user-images.githubusercontent.com/24985177/235105602-3b4c7618-2e95-40ff-81b8-25f94c342cd8.jpeg)
![image](https://user-images.githubusercontent.com/24985177/235105686-f92f9161-9115-4d67-b310-54dff83fbd05.jpeg)

**Comment by liaoliao666** [comment]
发一下帖子id

**Comment by Silent-wqh** [comment]
> 发一下帖子id

935809

**Comment by liaoliao666** [comment]
最新版已修复，不过为了修复这个问题，复制评论功能只支持复制全部文字。
