### ISSUE TITLE
Android app 希望支持查看 markdown 格式发布的贴子

### ISSUE THREAD

**Issue by QCuncle** [liaoliao666/v2ex#57]
亲爱的开发者，应用非常方便使用，但是和网页端相比来说，应用目前不支持正常查看 markdown 格式的帖子。希望能加上此功能。👍

**Comment by QCuncle** [comment]
我查看了一下到原生层的 视图树，整个文章的内容是显示在一个TextView上，内容是markdown格式的原文内容。

**Comment by liaoliao666** [comment]
请问是哪个帖子不支持查看

**Comment by QCuncle** [comment]
> 请问是哪个帖子不支持查看

**Comment by QCuncle** [comment]
> 请问是哪个帖子不支持查看

您好，是这个 https://www.v2ex.com/t/954046 下面的联系方式没有了，但是我不确定是我的帖子写的问题，还是v2ex返回的数据有问题，但是他在网页上可以正常看到联系方式

**Comment by QCuncle** [comment]
> 请问是哪个帖子不支持查看

我搜了搜其他的主题内容，markdown格式正常显示。也许这是v2ex的bug？😂

**Comment by liaoliao666** [comment]
我看了下，目前不支持在文字中内联图片。这个有点麻烦，也不知道能不能解决

**Comment by liaoliao666** [comment]
1.4.3已支持
