### ISSUE TITLE
特定帖子滑动到底部后闪退

### ISSUE THREAD

**Issue by moonheart** [liaoliao666/v2ex#59]
稳定复现 https://www.v2ex.com/t/954386

MIUI14 Android13

**Comment by liaoliao666** [comment]
我这边复现不了的话就没法修啊😂

**Comment by moonheart** [comment]
[log_2023_07_06_08_36_58.log](https://github.com/liaoliao666/v2ex/files/11963010/log_2023_07_06_08_36_58.log)
我用 logcat 抓了个日志不知道有没有用，我看到里面有崩溃日志

**Comment by liaoliao666** [comment]
https://expo.dev/artifacts/eas/savYc2zYPEmirA3EgrZjiy.apk
下载这个链接的试试

**Comment by moonheart** [comment]
ok 了，不闪退了
