### ISSUE TITLE
markdown长文本不自动换行

### ISSUE THREAD

**Issue by nadirvishun** [liaoliao666/v2ex#60]
当前版本：v1.4.0（貌似这个版本也有问题，我下载了最新的v1.4.3，安装后打开还是显示v1.4.0，还是提示更新）
平台：安卓
示例：[含长文本的主题](https://v2ex.com/t/956824)
用手机浏览器和app打开就能发现区别，app内出现横向的滚动条，而网页是可以正常换行的。

**Comment by liaoliao666** [comment]
因为如果是代码块需要横向滚动，而如果是文本则要换行。
目前没办法很清楚地显示的是代码块或者文本，所以这个问题目前解决不了。

至于版本问题，可以试着先卸载手机的版本，再重新下载

**Comment by nadirvishun** [comment]
卸载后重装可以了。
对代码块展示不是很了解，为什么网页版本的就可以正确识别呢，例如：[含长代码的主题](https://www.v2ex.com/t/956860)

**Comment by nadirvishun** [comment]
仔细看了下，网页版本也没有正确识别，还是换行了。

**Comment by nadirvishun** [comment]
这个确实不好处理，我看了下pc端的`typora`，它是专门有个配置可以选择是不是代码内换行。

**Comment by liaoliao666** [comment]
目前倒是有个机制是，经过处理之后判断有没有特殊样式的文本，有的话判断为代码块，没有则可以换行。
但是只是针对简单的文本可以，稍微复杂点还是会被判断为代码块。
所以确实是处理不了

**Comment by liaoliao666** [comment]
已支持识别非代码块自动换行
