### ISSUE TITLE
帖子内容多的时候滑动卡顿

### ISSUE THREAD

**Issue by moonheart** [liaoliao666/v2ex#61]
比如这个  https://www.v2ex.com/t/959084

设备是小米 12s ultra

**Comment by moonheart** [comment]
[log_2023_07_25_12_15_22.log](https://github.com/liaoliao666/v2ex/files/12157027/log_2023_07_25_12_15_22.log)

**Comment by liaoliao666** [comment]
这个是react native本身的性能问题，暂时找不到好的解决办法。
https://stackoverflow.com/questions/59691632/reactnative-android-extremely-slow-within-may-image-views

**Comment by liaoliao666** [comment]
https://github.com/liaoliao666/v2ex/issues/67
可以更新到最新的 app 我测了下改善还是蛮大的

**Comment by moonheart** [comment]
https://github.com/liaoliao666/v2ex/assets/15916990/18579dd3-83d6-48de-ace3-d3b31c3aeb4d

我试了下最新的这个 1.4.9，同样的帖子， 还是很卡，设备小米 12s ultra，Android 13，MIUI 14.0.14

**Comment by liaoliao666** [comment]
好吧，我再研究研究

**Comment by liaoliao666** [comment]
可以再试试1.5.0版本

**Comment by moonheart** [comment]
最新的 1.5.0 还是一样的，需要我这里抓点日志吗

**Comment by moonheart** [comment]
我换了一个安卓手机尝试，是很流畅的，我再排查下我这个手机的问题

**Comment by liaoliao666** [comment]
要不卸载重装试试

**Comment by liaoliao666** [comment]
https://github.com/liaoliao666/v2ex/releases/download/1.5.0/build-1695907098112.apk
试试这个，节前最后一个版本了

**Comment by moonheart** [comment]
😂 还是没对，先搁置了吧，影响也不是很大
