### ISSUE TITLE
希望可以增加一个回到顶部的功能

### ISSUE THREAD

**Issue by Aoang** [liaoliao666/v2ex#62]

**Comment by liaoliao666** [comment]
iOS的话，点击刘海就可以回到顶部了。
Android的话可以增加一个，这几天更新一下。

**Comment by Aoang** [comment]
> iOS的话，点击刘海就可以回到顶部了。 Android的话可以增加一个，这几天更新一下。

就是希望在 iOS 的底部加一个，方便单手操作。屏幕向下滚动时不会出现，向上滚动时出现

**Comment by liaoliao666** [comment]
已增加
