### ISSUE TITLE
增加双击tab快速刷新

### ISSUE THREAD

**Issue by CHEN1016** [liaoliao666/v2ex#63]
每次都要翻到最上面下拉刷新，可以加个双击返回最上方比并刷新的功能吗

**Comment by liaoliao666** [comment]
为什么要双击，单击不好么

**Comment by CHEN1016** [comment]
> 为什么要双击，单击不好么

单机不是简单的切换tab吗？我说的双击是刷新这个tab的文章

**Comment by liaoliao666** [comment]
在当前tab单击是刷新逻辑，点击到其它tab则是切换。

**Comment by CHEN1016** [comment]
> 在当前tab单击是刷新逻辑，点击到其它tab则是切换。

ios上好像不会处罚刷新

**Comment by liaoliao666** [comment]
已更新
