### ISSUE TITLE
新版本每次发送消息会提示发送失败，实际是成功的

### ISSUE THREAD

**Issue by hhjswf** [liaoliao666/v2ex#64]
![Screenshot_2023-09-15-13-20-56-94_737b16d9ed1b2276a8ea34ba9d309da8](https://github.com/liaoliao666/v2ex/assets/47738592/cee4ce94-e2de-44cf-a02d-3f8c9a9e368b)

**Comment by liaoliao666** [comment]
得过两天才能修了，周末不在家

**Comment by liaoliao666** [comment]
已修复
