### ISSUE TITLE
未读提醒会报错

### ISSUE THREAD

**Issue by RosenX** [liaoliao666/v2ex#66]
打开阅读提醒报错

![1](https://github.com/liaoliao666/v2ex/assets/8945794/4af6cab6-2f2b-44f6-9d74-b5dd1e444def)

**Comment by liaoliao666** [comment]
可以提供网页版的这个网页的请求结果么

**Comment by liaoliao666** [comment]
可以升级一下看看

**Comment by RosenX** [comment]
我把消息提醒页面的html下载到百度网盘了，https://pan.baidu.com/s/1Xy7XHrCHM0M63P9FHH329g?pwd=2vpa 提取码: 2vpa 

已经是最新版本了，还是报错

**Comment by liaoliao666** [comment]
https://expo.dev/artifacts/eas/t3xHKXpREsy3mutkmCVcHj.apk
试试这个链接的

**Comment by liuycy** [comment]
有个类似的问题，首页切换到”最近”tab页时，偶现如下报错![image](https://github.com/liaoliao666/v2ex/assets/55272688/a4084427-d144-48e3-bf40-26bd26c02039)

**Comment by RosenX** [comment]
> https://expo.dev/artifacts/eas/t3xHKXpREsy3mutkmCVcHj.apk 试试这个链接的

我是IOS的~

**Comment by liaoliao666** [comment]
@RosenX  😂过两天我发个版本

**Comment by liaoliao666** [comment]
已更新
