### ISSUE TITLE
帖子GIF多，闪退~ReactNative问题

### ISSUE THREAD

**Issue by androidcn** [liaoliao666/v2ex#67]
闪退的问题是因为那个帖子GIF太多了，而 ReactNative 对 GIF 支持太差，暂时没办法解决

**Comment by liaoliao666** [comment]
https://github.com/liaoliao666/v2ex/releases/download/1.4.8/build-1695787692196.apk
试试这个版本的

**Comment by liaoliao666** [comment]
https://github.com/liaoliao666/v2ex/releases/download/1.5.0/build-1695901213836.apk
1.5.0 新增了自动压缩 GIF 图功能
