### ISSUE TITLE
Android登录无法显示验证码

### ISSUE THREAD

**Issue by androidcn** [liaoliao666/v2ex#70]
![image](https://github.com/liaoliao666/v2ex/assets/271715/0a7a212a-0a08-4aa4-bef9-8121994f6f25)

![image](https://github.com/liaoliao666/v2ex/assets/271715/a0c7c23a-5aef-47df-a6c7-fbcf2b7137c0)

网页登录 可显示验证码图片

**Comment by liaoliao666** [comment]
我刚看了是有的，确保你现在版本是最新的了么

**Comment by liaoliao666** [comment]
https://github.com/liaoliao666/v2ex/releases/download/1.5.0/build-1695907098112.apk

**Comment by androidcn** [comment]
你这个版本就可以了
