### ISSUE TITLE
可以开发Hi-pda 4d4y论坛吗？

### ISSUE THREAD

**Issue by androidcn** [liaoliao666/v2ex#71]
iOS & Android

https://www.4d4y.com/forum/forumdisplay.php?fid=2

**Comment by liaoliao666** [comment]
如果是有偿可以考虑..

**Comment by androidcn** [comment]
> 如果是有偿可以考虑..

how much

**Comment by liaoliao666** [comment]
倒也不清楚市场价..
如果你仅仅是这个论坛的使用者的话，数额还是挺大，就此打住。
如果确实想开发，可以邮件联络
