### ISSUE TITLE
最新版本Android页面不正确

### ISSUE THREAD

**Issue by androidcn** [liaoliao666/v2ex#74]
![image](https://github.com/liaoliao666/v2ex/assets/271715/2404a778-74af-478e-b4cb-a668c520024d)

![image](https://github.com/liaoliao666/v2ex/assets/271715/e8be4cdd-81a0-4fb6-90a0-bedcf8df4363)

![image](https://github.com/liaoliao666/v2ex/assets/271715/57571d7b-efda-44fc-8554-48949d4635c9)

**Comment by liaoliao666** [comment]
https://github.com/liaoliao666/v2ex/releases/download/1.5.4/build-1697379515942.apk
更新这个就可以了

**Comment by androidcn** [comment]
![image](https://github.com/liaoliao666/v2ex/assets/271715/7dd5925b-9edb-49ea-8eb0-650755df34aa)

不行

横屏
首页不显示页面

转换 竖屏后 才能显示数据

![image](https://github.com/liaoliao666/v2ex/assets/271715/9abff990-7b30-4cdc-b04d-bbf627008626)

**Comment by liaoliao666** [comment]
https://github.com/liaoliao666/v2ex/releases/download/1.5.4/build-1697383154407.apk
这个可以了
