### ISSUE TITLE
操作不成功时仍然会显示成功

### ISSUE THREAD

**Issue by wydy** [liaoliao666/v2ex#76]
平台IOS，有些时候回复、感谢别人的时候显示成功了，但是一刷新其实没有成功，希望能修复一下判断

**Comment by liaoliao666** [comment]
比较麻烦的是我很难去复现回复失败的情况，所以很难去分析什么请求结果是失败的

**Comment by liaoliao666** [comment]
1.5.9版本已覆盖请求失败情况处理。
