### ISSUE TITLE
水深火热节点无法显示主题内容

### ISSUE THREAD

**Issue by JaminYe** [liaoliao666/v2ex#82]

**Comment by liaoliao666** [comment]
请确保你有权限访问水深火热节点，可以先去网页版确认

**Comment by JaminYe** [comment]
> 请确保你有权限访问水深火热节点，可以先去网页版确认

已确认可以显示，使用app中webview打开内容显示正常，浏览器亦正常

**Comment by JaminYe** [comment]
> 可以录屏或截图方便我排查吗，我这边是没问题的
这个节点下所有的主题内容展示的都是这样，webview中打开是没有问题的

![image](https://github.com/liaoliao666/v2ex/assets/45601795/166fd439-3b7b-4bb0-b187-4df21bc4ab34)
![image](https://github.com/liaoliao666/v2ex/assets/45601795/278f0c88-de40-44b0-8e6a-a746ae3c2e38)

**Comment by JaminYe** [comment]
忽略网络原因结果是相同的![image](https://github.com/liaoliao666/v2ex/assets/45601795/1c29d735-318d-4bc9-a5d9-0e884476a5b0)

**Comment by liaoliao666** [comment]
找到问题了，快的话明天早上你更新就可以解决了

**Comment by JaminYe** [comment]
> 找到问题了，快的话明天早上你更新就可以解决了

OK，感谢

**Comment by JaminYe** [comment]
最新版本已解决
