### ISSUE TITLE
您好，能否优化一下超长节点名的显示

### ISSUE THREAD

**Issue by jqyisbest** [liaoliao666/v2ex#83]
![image](https://github.com/liaoliao666/v2ex/assets/16437320/e6ea4465-844f-4fdb-821e-62ed0928f2d3)
![image](https://github.com/liaoliao666/v2ex/assets/16437320/812d40e1-3964-4854-baf9-1e56701327f8)

**Comment by liaoliao666** [comment]
下个版本会优化

**Comment by jqyisbest** [comment]
谢谢。希望能增加评论区楼层跳转功能，这个功能允许用户在评论区中跳转至其指定的楼层，在别的客户端中用过一下，挺方便的。

**Comment by liaoliao666** [comment]
根据目前的研究楼层跳转功能在 RN 上基本无法实现，如果你看到别的客户端有实现这个功能，那么应该不是基于 RN 的，或者跳转到指定楼层会有误差

**Comment by jqyisbest** [comment]
确实有误差。原来是受rn限制…谢谢你的解答。

**Comment by liaoliao666** [comment]
已更新在1.6.2版本

**Comment by jqyisbest** [comment]
> 已更新在1.6.2版本

好的，谢谢

**Comment by jqyisbest** [comment]
在默认字号下正常，调整字号以后标题之间的间距不一样
![image](https://github.com/liaoliao666/v2ex/assets/16437320/03f67fb0-c478-4182-ba5a-18f80b5d14c0)
能否做成标题间距相等的效果？
![image](https://github.com/liaoliao666/v2ex/assets/16437320/4fad6539-bbdd-4aa2-aad7-2f6ae01f6eb8)

**Comment by liaoliao666** [comment]
好的，我再研究一下

**Comment by jqyisbest** [comment]
好的，麻烦您了_(:_」∠)_

**Comment by liaoliao666** [comment]
最新版本已解决这个问题
