### ISSUE TITLE
贴子中的 gif 图片好像不会动

### ISSUE THREAD

**Issue by lonnywong** [liaoliao666/v2ex#88]
举例：https://www.v2ex.com/t/1010514
标题： `开源 ssh 客户端：支持自定义主题和颜色，看看你喜欢哪一种？`
问题：贴子中的 gif 图片好像不会动。

**Comment by liaoliao666** [comment]
是不会动，因为 RN 对 GIF 的支持极差，所以目前对 GIF 格式的图片会预处理为静态图以获得更好的滚动体验。
月底会更新一个版本，左上角会更新显示一个 GIF 标识，点开后可以直接预览 GIF，还有修复目前图片预览不能秒展示的问题。
还会更新主题系统，以下改动可以看下吗的演示
![v2ex_gif](https://github.com/liaoliao666/v2ex/assets/26479949/20d1651e-2f8e-4b1c-9ffc-c22112ba9f1f)

**Comment by lonnywong** [comment]
看起来可以，不过新用户可能不知道可以点击播放，可能 `GIF` 变成 `GIF - 点击播放` 会好一些？

**Comment by liaoliao666** [comment]
> 看起来可以，不过新用户可能不知道可以点击播放，可能 `GIF` 变成 `GIF - 点击播放` 会好一些？

这样改会不好看，而且点过一次也知道了。

**Comment by lonnywong** [comment]
问题不大，我是知道能点的了。当然最好是能自已动，又能兼顾其他的。

**Comment by liaoliao666** [comment]
已更新在1.6.2版本
