### ISSUE TITLE
已屏蔽用户主题贴不显示（竞品app中会显示

### ISSUE THREAD

**Issue by jqyisbest** [liaoliao666/v2ex#89]
在竞品app中，只屏蔽了已屏蔽用户的回复。请问这个屏蔽功能是v2ex实现的还是您在app中实现的？

**Comment by liaoliao666** [comment]
只是屏蔽回复的话，我这边是不会过滤掉的。
但是会有这个逻辑如果屏蔽了该用户我会过滤掉该用户的主题帖。你可以去屏蔽列表中确认是否屏蔽了该用户。

**Comment by jqyisbest** [comment]
明白了，谢谢解答。
可以考虑加入分级屏蔽功能吗？
- 屏蔽某用户的回复
- 屏蔽某用户的主题
- 屏蔽某用户的回复加主题

**Comment by liaoliao666** [comment]
暂不考虑

> 明白了，谢谢解答。 可以考虑加入分级屏蔽功能吗？
> 
> * 屏蔽某用户的回复
> * 屏蔽某用户的主题
> * 屏蔽某用户的回复加主题
