### ISSUE TITLE
显示问题

### ISSUE THREAD

**Issue by tuutoo** [liaoliao666/v2ex#92]
机器：小米14 pro
问题如图 
1 底部白边
2 用户那字体显示不全
![Screenshot_2024-01-30-13-30-10-603_com liaoliao666 v2ex](https://github.com/liaoliao666/v2ex/assets/9068314/de6c2e58-05d4-48b6-a1df-25c76a88783c)
![Screenshot_2024-01-30-13-30-18-664_com liaoliao666 v2ex](https://github.com/liaoliao666/v2ex/assets/9068314/cc488760-ece0-4a49-bb19-9d48734cf25d)

**Comment by tuutoo** [comment]
贴两张chatGPT应用的图，分别是浅色和深色模式下的。
![微信图片_20240130134118](https://github.com/liaoliao666/v2ex/assets/9068314/354d6b43-1a41-4a55-b21d-0383bf9ab7bb)
![微信图片_20240130134125](https://github.com/liaoliao666/v2ex/assets/9068314/60f4de9d-a59d-4aba-8f61-101f9ea9365e)

**Comment by liaoliao666** [comment]
https://expo.dev/artifacts/eas/dAdisABZiGonx2SKeJbAMh.apk
试试这个版本的

**Comment by tuutoo** [comment]
字体显示不全好了 但是暗黑模式下方的白条还有

liaoliao666 ***@***.***> 于 2024年1月30日周二 14:40写道：

**Comment by liaoliao666** [comment]
https://github.com/liaoliao666/v2ex/releases/tag/1.6.5
更新到1.6.5版本就可以了

**Comment by tuutoo** [comment]
谢谢 效率杠杠滴

里面是好了

还有个小问题 软件启动时的V字屏那里  还是有白边问题。我最初的截图那个

liaoliao666 ***@***.***> 于 2024年1月30日周二 19:17写道：

**Comment by liaoliao666** [comment]
@tuutoo 是启动一直有，还是v字屏结束时才有

**Comment by tuutoo** [comment]
就是刚开始启动时显示V字屏时一直存在，等到V字结束就没有了，到了显示网内容时就没有了。

另外这个V字显示的位置会向上有个位移。不是一直在中间。视觉上有位移。

liaoliao666 ***@***.***> 于 2024年1月30日周二 20:32写道：

**Comment by tuutoo** [comment]
https://github.com/liaoliao666/v2ex/assets/9068314/91f90fcc-9249-4cf1-841c-bd12a5e377b7

**Comment by liaoliao666** [comment]
https://github.com/liaoliao666/v2ex/releases/download/1.6.5/build-1706622591775.apk
@tuutoo 下载这个试试

**Comment by tuutoo** [comment]
https://github.com/liaoliao666/v2ex/assets/9068314/6f3654b1-a7ca-40c2-8fe9-8d73a2cf7378

可以了 
但是注意看V字向上有个位移，视觉上会有个跳动的感觉。如果这个能解决就更好了，并且最上面状态栏会闪一下白色的，和下方区域同一位置。有一瞬间的白色。

**Comment by liaoliao666** [comment]
倒是有思路了，这两天得空再优化一下

**Comment by tuutoo** [comment]
谢谢！不着急的

liaoliao666 ***@***.***> 于 2024年1月31日周三 17:45写道：

**Comment by liaoliao666** [comment]
https://github.com/liaoliao666/v2ex/releases/download/1.6.5/build-1706723983089.apk
下载这个试试

**Comment by tuutoo** [comment]
厉害厉害！
这个版本完美 :)

谢谢！

liaoliao666 ***@***.***> 于 2024年2月1日周四 02:00写道：
