### ISSUE TITLE
评论输入框不会随键盘抬升

### ISSUE THREAD

**Issue by lyizhuo** [liaoliao666/v2ex#95]
https://github.com/liaoliao666/v2ex/assets/64514694/17497c8d-b240-438c-ae0e-af36af7e3bf6

**Comment by ron159** [comment]
> https://expo.dev/artifacts/eas/hAKF6L277UL7NogutxNdRr.apk
> 试试这个版本的

最新版本还是有这个问题诶

Android 14
gboard 
1.67版本

**Comment by liaoliao666** [comment]
有点难搞，我这边没办法复现出来

**Comment by liaoliao666** [comment]
试试1.6.8版本，或许修复了

**Comment by ron159** [comment]
> 试试1.6.8版本，或许修复了

感谢 已修复
