### ISSUE TITLE
链接直接用浏览器打开

### ISSUE THREAD

**Issue by abelsep** [liaoliao666/v2ex#96]
链接用app自带的浏览器有时开不了或者很慢，希望能增加一个选项可以直接跳转浏览器打开，不需要先跳转app内，再去点“用浏览器打开”

**Comment by kuilei0926** [comment]
> 这个需求很怪，为什么不直接使用浏览器而是 App 呢

![Screenshot_2024-02-21-06-54-50-106_com coolapk market](https://github.com/liaoliao666/v2ex/assets/17094610/717e066b-0656-4074-8d7b-8ff17ccdf28d)
他的意思是内置的浏览器不好用，建议加这个功能

**Comment by liaoliao666** [comment]
已更新，可在设置页面更改
