### ISSUE TITLE
版本号错误

### ISSUE THREAD

**Issue by kuilei0926** [liaoliao666/v2ex#98]
安装的1.7.0，应用内的检测更新版本号显示为1.6.8 ，并且一直有提示更新的小红点

**Comment by liaoliao666** [comment]
再下载一次试试

**Comment by kuilei0926** [comment]
> 再下载一次试试

下载过很多次都是一样的

**Comment by kuilei0926** [comment]
> 再下载一次试试

清除缓存之后版本号正常了

**Comment by liaoliao666** [comment]
应该是你的网络问题，没有及时更新缓存

**Comment by kuilei0926** [comment]
> 应该是你的网络问题，没有及时更新缓存

每次更新后都要清理一遍缓存才能读取到正确的版本号
